config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "registrations"
  }

  devise_scope :user do
    authenticated :user do
      root 'posts#following_feed', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show]
  post "more_user_index", to: "users#more_user_index", as: :more_user_index
  post "more_user_show_posts/:id", to: "users#more_user_show_posts", as: :more_user_show_posts

  resources :posts
  post "more_index_posts", to: "posts#more_index_posts", as: :more_index_posts

  resources :posts do
    resources :comments, only: [:create, :update, :destroy] do
      member do
        post :ajax_feed_comment
      end
    end
  end

  post "more_comments/:post_id", to: "comments#more_comments", as: :more_comments

  get "/following_feed", to: "posts#following_feed"
  post "more_following_posts/:posts", to: "posts#more_following", as: :more_following

  get "/activity", to: "posts#activity"
  post "more_activity", to: "posts#more_activity", as: :more_activity

  get "/saved_posts", to: "saved_posts#saved_posts"
  post "more_saved_posts", to: "saved_posts#more_saved_posts", as: :more_saved_posts

  resources :video_posts

  resources :video_posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :likes, only: [:update] do
    member do
      put :ajax_likes_update
    end
  end

  resources :follows, only: [:update] do
    member do
      put :ajax_follows_update
    end
  end

  get "followers_index/:id", to: "follows#followers_index", as: :followers_index
  get "following_index/:id", to: "follows#following_index", as: :following_index

  resources :saved_posts, only: [:update] do
    member do
      put :ajax_saved_posts
    end
  end

  resources :conversations do
    resources :messages
  end

  post "more_conversations", to: "conversations#more_conversations", as: :more_conversations
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :body, presence: true, length: { maximum: 2200 }
  validates :conversation_id, presence: true
  validates :user_id, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:destroy]
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    session[:return_to] ||= request.referer

    @messages = @conversation.messages

    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end

    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
      @messages = @messages[0..@messages.length - 1]
    end

    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true
      end
    end

    @message = @conversation.messages.new

    temp_ary = []

    @messages.each do |msg|
      next if msg.id.nil?
      temp_ary << msg
    end

    @messages = temp_ary
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    @message.user_id = current_user.id

    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to conversation_messages_path(@conversation)
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def set_message
    if Message.find(params[:id]).user != current_user
      redirect_to session.delete(:return_to)
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<div id="messages-container">
  <% sender = User.find(@conversation.sender_id) %>
  <% recipient = User.find(@conversation.recipient_id) %>

  <div id="messages-header">
    <% other_user = current_user === sender ? recipient : sender %>

    <div>
      <%= link_to conversations_path, class: "messages-back-link" do %>
        <i class="fas fa-chevron-left"></i>
      <% end %>

      <%= link_to other_user.username, other_user, class: "messages-header-username" %>
    </div>

    <%= link_to @conversation, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="far fa-trash-alt messages-conversation-del-link"></i>
    <% end %>
  </div>

  <div id="messages-parent-div">
    <% if @over_ten %>
      <%= link_to "Show All", '?m=all', class: "top-message-links" %>
    <% end %>

    <% @messages.each do |message| %>
      <% user = User.find(message.user_id) %>

      <% if current_user === user %>
        <div class="current-user-msg-container">
          <p class="message-date">
            <%= message.created_at.localtime.strftime("%B %e, %Y  %l:%M %p") %>
          </p>

          <div class="current-user-message-body-div">
            <%= link_to conversation_message_path(@conversation.id, message.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "msg-delete-link" do %>
              <i class="far fa-trash-alt"></i>
            <% end %>

            <p class="current-user-message-body">
              <% if message.body.length > 200 %>
                <%= message.body[0..200] %><span class="show-more">...Show More</span><span class="more-content"><%= message.body[200..message.body.length] %></span><span class="show-less">...Show Less</span>
              <% else %>
                <%= message.body %>
              <% end %>
            </p>
          </div>
        </div>
      <% else %>

        <div class="other-user-message-container">
          <%= link_to user do %>
            <% if user.avatar.attached? %> 
              <div class="message-avatar background-image" style="background-image: url('<%= url_for(user.avatar) %>');"></div>
            <% else %>
              <div class="message-avatar background-image" style="background-image: url('<%= "/assets/default_profile.jpg" %>');"></div>
            <% end %>
          <% end %>

          <div>
            <p class="other-user-username"><%= user.username %></p>
            <p class="other-user-message-body">
              <% if message.body.length > 150 %>
                <%= message.body[0..150] %><span class="show-more">...Show More</span><span class="more-content"><%= message.body[150..message.body.length] %></span><span class="show-less">...Show Less</span>
              <% else %>
                <%= message.body %>
              <% end %>
            </p>
          </div>
        </div>

      <% end %>
    <% end %>
  </div>

  <div id="message-form-container">
    <%= form_for [@conversation, @message], html: {class: "message-form"} do |f| %>
      <%= f.text_area :body, placeholder: "Message...", class: "message-text-area", required: true, minlength: "1", maxlength: "2200" %>
      <%= f.submit "Send", class: "message-submit" %>
    <% end %>
  </div>

</div>