config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "registrations"
  }

  devise_scope :user do
    authenticated :user do
      root 'posts#following_feed', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show]
  post "more_user_index", to: "users#more_user_index", as: :more_user_index
  post "more_user_show_posts/:id", to: "users#more_user_show_posts", as: :more_user_show_posts

  resources :posts
  post "more_index_posts", to: "posts#more_index_posts", as: :more_index_posts

  resources :posts do
    resources :comments, only: [:create, :update, :destroy] do
      member do
        post :ajax_feed_comment
      end
    end
  end

  post "more_comments/:post_id", to: "comments#more_comments", as: :more_comments

  get "/following_feed", to: "posts#following_feed"
  post "more_following_posts/:posts", to: "posts#more_following", as: :more_following

  get "/activity", to: "posts#activity"
  post "more_activity", to: "posts#more_activity", as: :more_activity

  get "/saved_posts", to: "saved_posts#saved_posts"
  post "more_saved_posts", to: "saved_posts#more_saved_posts", as: :more_saved_posts

  resources :video_posts

  resources :video_posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :likes, only: [:update] do
    member do
      put :ajax_likes_update
    end
  end

  resources :follows, only: [:update] do
    member do
      put :ajax_follows_update
    end
  end

  get "followers_index/:id", to: "follows#followers_index", as: :followers_index
  get "following_index/:id", to: "follows#following_index", as: :following_index

  resources :saved_posts, only: [:update] do
    member do
      put :ajax_saved_posts
    end
  end

  resources :conversations do
    resources :messages
  end

  post "more_conversations", to: "conversations#more_conversations", as: :more_conversations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, dependent: :destroy
  has_many :video_posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :follows

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Follow"
  has_many :followers, through: :follower_relationships, source: :follower, dependent: :destroy

  has_many :following_relationships, foreign_key: "user_id", class_name: "Follow"
  has_many :following, through: :following_relationships, source: :following, dependent: :destroy

  has_many :saved_posts, dependent: :destroy

  has_many :sender_conversations, foreign_key: "sender_id", class_name: "Conversation", dependent: :destroy

  has_many :receiver_conversations, foreign_key: "recipient_id", class_name: "Conversation", dependent: :destroy
  
  has_many :messages, dependent: :destroy
  
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9]+\z/
  validates :username, uniqueness: true, case_sensitive: false, presence: true, length: {minimum: 4, maximum: 16}, format: { with: VALID_USERNAME_REGEX }

  validates :first_name, :last_name, presence: true, length: { minimum: 1, maximum: 60 }

  validates :bio, length: { maximum: 150 }

  has_one_attached :avatar, dependent: :destroy
  validate :avatar_type

  private

  def avatar_type
    if avatar.attached?
      if !avatar.content_type.in?(%('image/jpeg image/jpg image/png'))
        errors.add(:avatar, "needs to be JPG or PNG")
      end
    else
      'default_profile.jpg'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search]
      search_txt = params[:search].downcase
      @users = []

      search_words = search_txt.split(" ")
      
      User.all.select do |user|
        next if current_user === user

        search_words.each do |word|
          if user.first_name.downcase[word] || user.last_name.downcase[word] || user.username.downcase[word]
            @users << user
          end
        end
      end

      @users.uniq!

    else
      @users = []
      User.all.each do |user|
        @users << user
      end
    end
  end

  def more_user_index
    @next_start_point = params[:next].to_i

    if params[:type] === "search"
      search_txt = params[:search].downcase
      @users = []

      search_words = search_txt.split(" ")
      
      User.all.select do |user|
        next if current_user === user

        search_words.each do |word|
          if user.first_name.downcase[word] || user.last_name.downcase[word] || user.username.downcase[word]
            @users << user
          end
        end
      end

      @users.uniq!

      temp_ary = []

      13.times do
        next if @users[@next_start_point].nil?
        temp_ary << @users[@next_start_point]
        @next_start_point += 1
      end
      
      @users = temp_ary

    else
      @users = []
      User.all.each do |user|
        @users << user
      end

      temp_ary = []

      13.times do
        next if @users[@next_start_point].nil?
        temp_ary << @users[@next_start_point]
        @next_start_point += 1
      end
      
      @users = temp_ary
    end

    respond_to do |format|
      format.js { render "users/more_user_index" }
    end
  end

  def show
    @user = User.find(params[:id])

    @user_posts = (@user.posts + @user.video_posts).sort_by(&:created_at).reverse!
  end

  def more_user_show_posts
    @next_start_point = params[:next].to_i
    @user = User.find(params[:id])

    @user_posts = (@user.posts + @user.video_posts).sort_by(&:created_at).reverse!

    temp_ary = []

    21.times do
      next if @user_posts[@next_start_point].nil?
      temp_ary << @user_posts[@next_start_point]
      @next_start_point += 1
    end
    
    @user_posts = temp_ary

    respond_to do |format|
      format.js { render "users/more_user_show_posts" }
    end
  end

  private

  def search_params
    params.require(:user).permit(:search)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% if params[:search] && @users.length === 0 %>
  <div id="ui-no-result-div">
    <div id="ui-no-results-center-div">
      <%= form_tag(users_path, method: :get, id: "user-index-form") do %>
        <%= text_field_tag(:search, params[:search], placeholder: "search", id: "user-index-search") %>

        <button id="user-index-search-btn" type="submit" name="commit">
          <i class="fas fa-search"></i>
        </button>
      <% end %>

      <h1 id="ui-no-result">No Results Found For "<%= params[:search] %>"</h1>
    </div>

  </div>
<% else %>
  <div id="user-index-container">

    <%= form_tag(users_path, method: :get, id: "user-index-form") do %>
      <%= text_field_tag(:search, params[:search], placeholder: "search", id: "user-index-search") %>

      <button id="user-index-search-btn" type="submit" name="commit">
        <i class="fas fa-search"></i>
      </button>
    <% end %>

    <% @users[0, 12].each do |user| %>
      <% next if current_user === user %>

      <div class="user-index-user-container">

        <div class="user-index-ava-un-div" onclick="location.href='<%= url_for(user) %>'">
          <% if user.avatar.attached? %> 
            <div class="user-index-avatar background-image" style="background-image: url('<%= url_for(user.avatar) %>');"></div>
          <% else %>
            <div class="user-index-avatar background-image" style="background-image: url('<%= "/assets/default_profile.jpg" %>');"></div>
          <% end %>

          <div>
            <%= link_to user.username, user, class: "user-index-username" %>
            <p class="user-index-fullname">
              <%= "#{user.first_name} #{user.last_name}" %>
            </p>
          </div>
        </div>

        <% @follow = Follow.find_by(user_id: current_user.id, following_id: user.id) %>
        <% follow_txt = @follow ? "Unfollow" : "Follow" %>

        <%= link_to follow_txt, ajax_follows_update_follow_path(user_id: current_user.id, following_id: user.id, html_id: "follow-#{user.id}", id: 0), method: :put, remote: true, id: "follow-#{user.id}", class: "user-index-follow-link" %>

      </div>
    <% end %>

  </div>

  <% view_type = params[:search] ? "search" : "all" %>

  <% if @users.length > 13 %>
    <%= link_to "Show More...", more_user_index_path(next: 13, type: view_type, search: params[:search]), method: :post, remote: true, id: "more-link", class: "bottom-links" %>

    <button id="top-link" class="bottom-links">Back to top</button>
  <% end %>
<% end %>

app/views/users/more_user_index.js.erb
var moreLink = document.getElementById("more-link");

<% if @users.length === 0 %>
  // Back to top link when there are no more posts to show
  moreLink.style.display = "none";
  document.getElementById("top-link").style.display = "block";
<% else %>
  // Make href request for next 10 posts
  moreLink.href = "/more_user_index?next=<%= @next_start_point %>&search=<%= params[:search] %>&type=<%= params[:type] %>";
<% end %>

var parentDiv = document.getElementById("user-index-container");

<% @users.each do |user| %>
  <% next if current_user === user %>

  // Create user container
  var userDiv = document.createElement("div");
  userDiv.classList.add("user-index-user-container");
  parentDiv.appendChild(userDiv);

  // Create div for username and avatar
  var unDiv = document.createElement("div");
  unDiv.classList.add("user-index-ava-un-div");
  unDiv.onclick = () => {
    location.href = "<%= url_for(user) %>";
  };
  userDiv.appendChild(unDiv);

  // Create user avatar
  var userAvatar = document.createElement("div");
  userAvatar.classList.add("user-index-avatar");
  userAvatar.classList.add("background-image");

  <% if user.avatar.attached? %>
    userAvatar.style.backgroundImage = "url('<%= url_for(user.avatar) %>')";
  <% else %>
    userAvatar.style.backgroundImage = "url('<%= "/assets/default_profile.jpg" %>')";
  <% end %>
  unDiv.appendChild(userAvatar);

  // Create username div
  var innerUnDiv = document.createElement("div");
  unDiv.appendChild(innerUnDiv);

  // Create username link
  var unLink = document.createElement("a");
  unLink.href = "<%= url_for(user) %>";
  unLink.textContent = "<%= user.username %>";
  unLink.classList.add("user-index-username");
  innerUnDiv.appendChild(unLink);

  // Create user full name
  var uFullname = document.createElement("p");
  uFullname.classList.add("user-index-fullname");
  uFullname.textContent = "<%= "#{user.first_name} #{user.last_name}" %>";
  innerUnDiv.appendChild(uFullname);

  <% follow = Follow.find_by(user_id: current_user.id, following_id: user.id) %>
  <% follow_txt = follow ? "Unfollow" : "Follow" %>

  // Create Follow link
  var followLink = document.createElement("a");
  followLink.id = "<%= "follow-#{user.id}" %>";
  followLink.classList.add("user-index-follow-link");
  followLink.setAttribute("data-remote", "true");
  followLink.setAttribute("data-method", "put");
  followLink.textContent = "<%= follow_txt %>";
  followLink.href = "<%= raw ajax_follows_update_follow_path(user_id: current_user.id, following_id: user.id, html_id: "follow-#{user.id}", id: 0) %>";
  userDiv.appendChild(followLink);

  <% end %>

app/views/users/more_user_show_posts.js.erb
var moreLink = document.getElementById("more-link");

<% if @user_posts.length === 0 %>
  // Back to top link when there are no more posts to show
  moreLink.style.display = "none";
  document.getElementById("top-link").style.display = "block";
<% else %>
  // Make href request for next 10 posts
  moreLink.href = "/more_user_show_posts/<%= @user.id %>?next=<%= @next_start_point %>>";
<% end %>

var parentDiv = document.getElementById("user-sh-post-grid");

<% @user_posts.each do |post| %>

  <% if post.class.method_defined? :image %>
    // Create post link
    var postLink = document.createElement("a");
    postLink.href = "<%= url_for(post) %>";
    postLink.classList.add("user-sh-post-link");
    parentDiv.appendChild(postLink);

    // Create post image div
    var postImageDiv = document.createElement("div");
    postImageDiv.classList.add("user-sh-tile-div");
    postImageDiv.classList.add("background-image");
    postImageDiv.style.backgroundImage = "url('<%= url_for(post.image) %>')";
    postLink.appendChild(postImageDiv);

    // Create tinted tile Div
    var tintedDiv = document.createElement("div");
    tintedDiv.classList.add("tinted-tile");
    postImageDiv.appendChild(tintedDiv);

    // Create p tag with post info
    var pInfo = document.createElement("p");
    pInfo.classList.add("post-index-info");
    tintedDiv.appendChild(pInfo);

    // Create like icon
    var pHeart = document.createElement("i");
    pHeart.classList.add("fas");
    pHeart.classList.add("fa-heart");
    pHeart.classList.add("us-icon");
    pInfo.appendChild(pHeart);

    // Create like count span
    var likeCount = document.createElement("span");
    likeCount.classList.add("us-icon-like");
    likeCount.textContent = "<%= post.likes.count %>";
    pInfo.appendChild(likeCount);

    // Create comment icon
    var commentIcon = document.createElement("i");
    commentIcon.classList.add("fas");
    commentIcon.classList.add("fa-comment");
    commentIcon.classList.add("us-icon");
    pInfo.appendChild(commentIcon);

    // Create comments count span
    var commentCount = document.createElement("span");
    commentCount.textContent = "<%= post.comments.count %>";
    pInfo.appendChild(commentCount);

  <% elsif post.class.method_defined? :clip %>
    // Create post link
    var postLink = document.createElement("a");
    postLink.href = "<%= url_for(post) %>";
    postLink.classList.add("user-sh-post-link");
    parentDiv.appendChild(postLink);

    // Create post video div
    var postVideoDiv = document.createElement("div");
    postVideoDiv.classList.add("user-sh-tile-div");
    postVideoDiv.classList.add("video-container");
    postLink.appendChild(postVideoDiv);

    // Create video tag
    var postVideo = document.createElement("video");
    postVideo.classList.add("user-sh-video");
    postVideo.src = "<%= url_for(post.clip) %>";
    postVideoDiv.appendChild(postVideo);

    // Create tinted tile Div
    var tintedDiv = document.createElement("div");
    tintedDiv.classList.add("tinted-tile");
    postVideoDiv.appendChild(tintedDiv);

    // Create p tag with post info
    var pInfo = document.createElement("p");
    pInfo.classList.add("post-index-info");
    tintedDiv.appendChild(pInfo);

    // Create like icon
    var pHeart = document.createElement("i");
    pHeart.classList.add("fas");
    pHeart.classList.add("fa-heart");
    pHeart.classList.add("us-icon");
    pInfo.appendChild(pHeart);

    // Create like count span
    var likeCount = document.createElement("span");
    likeCount.classList.add("us-icon-like");
    likeCount.textContent = "<%= post.likes.count %>";
    pInfo.appendChild(likeCount);

    // Create comment icon
    var commentIcon = document.createElement("i");
    commentIcon.classList.add("fas");
    commentIcon.classList.add("fa-comment");
    commentIcon.classList.add("us-icon");
    pInfo.appendChild(commentIcon);

    // Create comments count span
    var commentCount = document.createElement("span");
    commentCount.textContent = "<%= post.comments.count %>";
    pInfo.appendChild(commentCount);
  <% end %>
<% end %>

// Add tinted tiles event listeners
var tintedTiles = document.querySelectorAll(".tinted-tile");

tintedTiles.forEach((tile) => {
  tile.addEventListener("mouseenter", () => {
    tile.style.backgroundColor = "rgba(0, 0, 0, 0.5)";
    tile.childNodes[0].style.display = "block";
  });

  tile.addEventListener("mouseleave", () => {
    tile.style.backgroundColor = "rgba(0, 0, 0, 0.0)";
    tile.childNodes[0].style.display = "none";
  });
});

app/views/users/show.html.erb
<div id="user-sh-container">

  <div id="user-sh-header-info">

    <% if @user.avatar.attached? %> 
      <div class="user-sh-avatar background-image" style="background-image: url('<%= url_for(@user.avatar) %>');"></div>
    <% else %>
      <div class="user-sh-avatar background-image" style="background-image: url('<%= "/assets/default_profile.jpg" %>');"></div>
    <% end %>

    <div>

      <div id="user-sh-info-1">
        <p class="user-sh-username"><%= @user.username %></p>

        <% if current_user != @user %>
          <div id="user-sh-mnf-links">
            <%= link_to "Message", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: "post", class: "user-sh-mnf-link" %>

            <% @follow = Follow.find_by(user_id: current_user.id, following_id: @user.id) %>

            <% follow_txt = @follow ? "Unfollow" : "Follow" %>

            <%= link_to follow_txt, ajax_follows_update_follow_path(user_id: current_user.id, following_id: @user.id, html_id: "follow-#{@user.id}"), method: :put, remote: true, id: "follow-#{@user.id}", class: "user-sh-mnf-link" %>
          </div>

        <% else %>
          <%= link_to edit_user_registration_path, id: "user-sh-edit-link" do %>
            <span class="user-sh-edit-txt">Edit Profile</span>
            <span class="user-sh-cog"><i class="fas fa-cog"></i></span>
          <% end %>
        <% end %>
      </div>

      <div id="user-sh-info-2">
        <p class="user-sh-info-stats">
          <strong><%= @user.posts.count + @user.video_posts.count %></strong> <%= "post".pluralize(@user.posts.count) %>
        </p>

        <% if @user.followers.count === 0 %>
          <p class="user-sh-info-stats">
            <strong><%= @user.followers.count %></strong> <%= "follower".pluralize(@user.followers.count) %>
          </p>
        <% else %>
          <%= link_to followers_index_path(@user.id), class: "user-show-follow-index-link" do %>
            <p class="user-sh-info-stats">
              <strong><%= simple_number(@user.followers.count) %></strong> <%= "follower".pluralize(@user.followers.count) %>
            </p>
          <% end %>
        <% end %>

        <% if @user.following.count === 0 %>
          <p class="user-sh-info-stats">
            <strong><%= @user.following.count %></strong> following
          </p>
        <% else %>
          <%= link_to following_index_path(@user.id), class: "user-show-follow-index-link" do %>
            <p class="user-sh-info-stats">
              <strong><%= simple_number(@user.following.count) %></strong> following
            </p>
          <% end %>
        <% end %>

      </div>

      <h3 id="user-sh-fullname">
        <%= "#{@user.first_name.downcase.capitalize} #{@user.last_name.downcase.capitalize}" %>
      </h3>

      <% if @user.bio === nil || @user.bio.strip != "" %>
        <p id="user-sh-bio">
          <%= @user.bio %>
        </p>
      <% end %>

    </div>
  </div>

  <div id="user-sh-parent-info-div">
    <div id="user-sh-post-header-links">

      <% if current_user === @user %>
        <%= link_to new_post_path, class: "user-sh-sp" do %>
          <i class="far fa-plus-square user-sh-plus-icon"></i> New Post
        <% end %>
      <% end %>

      <p class="user-sh-sp"><i class="fas fa-th user-sh-th"></i> Posts<p>

      <% if current_user === @user %>
        <%= link_to saved_posts_path, class: "user-sh-sp" do %>
          <p><i class="far fa-bookmark user-sh-bookmark"></i> Saved</p>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if @user_posts.length != 0 %>
    
    <div id="user-sh-post-grid">
      <% @user_posts[0, 21].each do |post| %>

        <% if post.class.method_defined? :image %>

          <%= link_to post, class: "user-sh-post-link" do %>
            <div class="user-sh-tile-div background-image" style="background-image: url('<%= url_for(post.image) %>');">

              <div class="tinted-tile">
                <p class="post-index-info">
                  <i class="fas fa-heart us-icon"></i>
                  <span class="us-icon-like">
                    <%= post.likes.count %>
                  </span>
                  
                  <i class="fas fa-comment us-icon"></i>
                  <span>
                    <%= post.comments.count %>
                  </span>
                </p>
              </div>
              
            </div>
          <% end %>
          
        <% elsif post.class.method_defined? :clip %>

          <%= link_to post, class: "user-sh-post-link" do %>
            <div class="user-sh-tile-div video-container">
              <%= video_tag url_for(post.clip), class: "user-sh-video" %>

              <div class="tinted-tile">
                <p class="post-index-info">
                  <i class="fas fa-heart us-icon"></i>
                  <span class="us-icon-like">
                    <%= post.likes.count %>
                  </span>

                  <i class="fas fa-comment us-icon"></i>
                  <span>
                    <%= post.comments.count %>
                  </span>
                </p>
              </div>
            </div>
          <% end %>

        <% end %>

      <% end %>
    </div>
  <% else %>
    <% if current_user === @user %>
      <div class="user-show-no-posts">
        <h1 class="user-show-no-posts-title-current-user">You haven't posted anything!</h1>
        <%= link_to "Share", new_post_path, id: "user-show-add-post-current-user" %>
      </div>

    <% else %>
      <div class="user-show-no-posts">
        <i class="fas fa-camera user-show-no-posts-camera"></i>
        <h2 class="user-show-no-posts-title-current-user">No Posts Yet</h2>
      </div>
    <% end %>
  <% end %>
</div>

<% if @user_posts.length > 21 %>
  <%= link_to "More posts...", more_user_show_posts_path(id: @user.id, next: 21), method: :post, remote: true, id: "more-link", class: "bottom-links" %>

  <button id="top-link" class="bottom-links">Back to top</button>
<% end %>