config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "registrations"
  }

  devise_scope :user do
    authenticated :user do
      root 'posts#following_feed', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show]
  post "more_user_index", to: "users#more_user_index", as: :more_user_index
  post "more_user_show_posts/:id", to: "users#more_user_show_posts", as: :more_user_show_posts

  resources :posts
  post "more_index_posts", to: "posts#more_index_posts", as: :more_index_posts

  resources :posts do
    resources :comments, only: [:create, :update, :destroy] do
      member do
        post :ajax_feed_comment
      end
    end
  end

  post "more_comments/:post_id", to: "comments#more_comments", as: :more_comments

  get "/following_feed", to: "posts#following_feed"
  post "more_following_posts/:posts", to: "posts#more_following", as: :more_following

  get "/activity", to: "posts#activity"
  post "more_activity", to: "posts#more_activity", as: :more_activity

  get "/saved_posts", to: "saved_posts#saved_posts"
  post "more_saved_posts", to: "saved_posts#more_saved_posts", as: :more_saved_posts

  resources :video_posts

  resources :video_posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :likes, only: [:update] do
    member do
      put :ajax_likes_update
    end
  end

  resources :follows, only: [:update] do
    member do
      put :ajax_follows_update
    end
  end

  get "followers_index/:id", to: "follows#followers_index", as: :followers_index
  get "following_index/:id", to: "follows#following_index", as: :following_index

  resources :saved_posts, only: [:update] do
    member do
      put :ajax_saved_posts
    end
  end

  resources :conversations do
    resources :messages
  end

  post "more_conversations", to: "conversations#more_conversations", as: :more_conversations
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :saved_posts, dependent: :destroy

  validates :caption, length: { maximum: 2200 }

  has_one_attached :image, dependent: :destroy
  validates :image, presence: true

  validate :image_type, unless: ->(x) { x.image.blank? }
  
  private

  def image_type
    if image.attached? && !image.content_type.in?(%(image/jpeg image/png))
      errors.add(:image, "must be a JPEG or PNG.")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
    posts = Post.all + VideoPost.all
    temp_ary = []
    @sorted_by_likes = []

    posts.each do |post|
      temp_ary << { likes: post.likes.count, post_obj: post }
    end

    temp_ary = (temp_ary.sort_by { |x| x[:likes] }).reverse!
    
    temp_ary.each do |obj|
      @sorted_by_likes << obj[:post_obj]
    end
  end

  def more_index_posts
    @next_start_point = params[:next].to_i

    posts = Post.all + VideoPost.all
    temp_ary = []
    @sorted_by_likes = []

    posts.each do |post|
      temp_ary << { likes: post.likes.count, post_obj: post }
    end

    temp_ary = (temp_ary.sort_by { |x| x[:likes] }).reverse!
    
    temp_ary.each do |obj|
      @sorted_by_likes << obj[:post_obj]
    end

    temp_ary2 = []

    21.times do
      next if @sorted_by_likes[@next_start_point].nil?
      temp_ary2 << @sorted_by_likes[@next_start_point]
      @next_start_point += 1
    end
    
    @sorted_by_likes = temp_ary2

    respond_to do |format|
      format.js { render "posts/more_index_posts" }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post
    else 
      flash.now[:danger] = "Can't create this Post, there are errors."
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @comment = Comment.new

    all_comments = @post.comments 

    temp_ary = []
    @comments = []

    all_comments.each do |comment|
      temp_ary << { likes: comment.likes.count, com_obj: comment }
    end

    temp_ary = (temp_ary.sort_by { |x| x[:likes] }).reverse!
    
    temp_ary.each do |obj|
      @comments << obj[:com_obj]
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.user_id = current_user.id
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to current_user
  end

  def following_feed
    @comment = Comment.new
    @following = current_user.following
    @following_posts = []

    @following.each do |user|
      user.posts.each do |post|
        @following_posts << post
      end

      user.video_posts.each do |post|
        @following_posts << post
      end
    end

    @sorted_feed = @following_posts.sort_by(&:created_at).reverse!
  end

  def more_following
    @next_start_point = params[:next].to_i

    @following = current_user.following
    @following_posts = []

    @following.each do |user|
      user.posts.each do |post|
        @following_posts << post
      end

      user.video_posts.each do |post|
        @following_posts << post
      end
    end

    @sorted_feed = @following_posts.sort_by(&:created_at).reverse!

    temp_ary = []

    10.times do
      next if @sorted_feed[@next_start_point].nil?
      temp_ary << @sorted_feed[@next_start_point]
      @next_start_point += 1
    end
    
    @sorted_feed = temp_ary

    respond_to do |format|
      format.js { render "posts/more_following" }
    end
  end

  def activity
    all_likes = []
    all_comments = []

    current_user.posts.each do |post|
      post.likes.each do |like|
        next if current_user.id === like.user_id
        all_likes << like
      end
    end

    current_user.video_posts.each do |post|
      post.likes.each do |like|
        next if current_user.id === like.user_id
        all_likes << like
      end
    end

    current_user.posts.each do |post|
      post.comments.each do |comment|
        next if current_user.id === comment.user_id
        all_comments << comment
      end
    end

    current_user.video_posts.each do |post|
      post.comments.each do |comment|
        next if current_user.id === comment.user_id
        all_comments << comment
      end
    end

    follows = Follow.where(following_id: current_user.id)

    @activity = (all_likes + all_comments + follows).sort_by(&:created_at).reverse!
  end

  def more_activity
    all_likes = []
    all_comments = []

    current_user.posts.each do |post|
      post.likes.each do |like|
        next if current_user.id === like.user_id
        all_likes << like
      end
    end

    current_user.video_posts.each do |post|
      post.likes.each do |like|
        next if current_user.id === like.user_id
        all_likes << like
      end
    end

    current_user.posts.each do |post|
      post.comments.each do |comment|
        next if current_user.id === comment.user_id
        all_comments << comment
      end
    end

    current_user.video_posts.each do |post|
      post.comments.each do |comment|
        next if current_user.id === comment.user_id
        all_comments << comment
      end
    end

    follows = Follow.where(following_id: current_user.id)

    @activity = (all_likes + all_comments + follows).sort_by(&:created_at).reverse!

    @next_start_point = params[:next].to_i

    temp_ary = []

    13.times do
      next if @activity[@next_start_point].nil?
      temp_ary << @activity[@next_start_point]
      @next_start_point += 1
    end
    
    @activity = temp_ary

    respond_to do |format|
      format.js { render "posts/more_activity" }
    end
  end

  private

  def post_params
    params.require(:post).permit(:caption, :image)
  end

  def set_post
    if Post.find(params[:id]).user != current_user
      redirect_to posts_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div>
  <% if @post.errors.any? %>
    <div id="post-form-error-container">
      <p id="post-form-flash-danger"><%= flash[:danger] %></p>
      <ul id="post-form-error-ul">
        <% @post.errors.full_messages.each do |msg| %>
          <li class="post-form-error-list-item"><span><%= msg %></span></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form_with model: @post, local: true, class: "post-new-form" do |f| %>
    <% if @post.image.attached? && @post.image.content_type.in?(%(image/jpeg image/png)) %>
      <div class="post-edit-image background-image" style="background-image: url('<%= url_for(@post.image) %>');"></div>
    <% end %>

    <div>
      <%= f.file_field :image, id: "primary-file-input" %>
      <p id="choose-file" class="post-new-choose-image">Choose Image...</p>
    </div>

    <%= f.text_area :caption, placeholder: "Write a caption...", id: "post-new-text-area" %>

    <%= f.submit "Share", id: "new-post-submit-btn" %>
  <% end %>
</div>

app/views/posts/activity.html.erb
<% if @activity.length === 0 %>
  <div id="post-activity-no-act-div">
    <h1 id="no-act-title">No Activity Yet</h1>
    <h3 id="no-act-description">See all your comment and likes here</h3>
  </div>
<% else %>
  <div id="post-activity-container">
    <% @activity[0, 13].each do |activity| %>
      <% user = User.find(activity.user_id) %>

      <% if activity.class.name === "Like" %>

        <% if activity.post_id != nil %>
          <% post = Post.find(activity.post_id) %>
        <% elsif activity.video_post_id != nil %>
          <% post = VideoPost.find(activity.video_post_id) %>
        <% end %>

        <div class="activity-like-container">
          <%= link_to user do %>
            <% if user.avatar.attached? %> 
              <div class="post-activity-avatar background-image" style="background-image: url('<%= url_for(user.avatar) %>');"></div>
            <% else %>
              <div class="post-activity-avatar background-image" style="background-image: url('<%= "/assets/default_profile.jpg" %>');"></div>
            <% end %>
          <% end %>

          <p class="post-activity-text post-activity-desc">
            <%= link_to user.username, user, class: "post-activity-un" %> <%= link_to "liked your photo", post, class: "post-activity-post-link" %>
          </p>

          <p class="post-activity-time post-activity-text">
            <%= time_ago_in_words(activity.created_at.localtime) %> ago
          </p>
        </div>

      <% elsif activity.class.name === "Comment" %>
        
        <% if activity.post_id != nil %>
          <% post = Post.find(activity.post_id) %>
        <% elsif activity.video_post_id != nil %>
          <% post = VideoPost.find(activity.video_post_id) %>
        <% end %>

        <div class="activity-like-container">
          <%= link_to user do %>
            <% if user.avatar.attached? %> 
              <div class="post-activity-avatar background-image" style="background-image: url('<%= url_for(user.avatar) %>');"></div>
            <% else %>
              <div class="post-activity-avatar background-image" style="background-image: url('<%= "/assets/default_profile.jpg" %>');"></div>
            <% end %>
          <% end %>

          <p class="post-activity-text post-activity-desc">
            <%= link_to user.username, user, class: "post-activity-un" %> 
            <%= link_to "commented: #{activity.body.length > 40 ? activity.body[0..40] + "..." : activity.body}", post, class: "post-activity-post-link" %> 
          </p>

          <p class="post-activity-time post-activity-text">
            <%= time_ago_in_words(activity.created_at.localtime) %> ago
          </p>
        </div>
      <% elsif activity.class.name === "Follow" %>
        <div class="activity-like-container">
          <%= link_to user do %>
            <% if user.avatar.attached? %> 
              <div class="post-activity-avatar background-image" style="background-image: url('<%= url_for(user.avatar) %>');"></div>
            <% else %>
              <div class="post-activity-avatar background-image" style="background-image: url('<%= "/assets/default_profile.jpg" %>');"></div>
            <% end %>
          <% end %>

          <p class="post-activity-text post-activity-desc">
            <%= link_to user.username, user, class: "post-activity-un" %> <%= link_to "started following you", user, class: "post-activity-post-link" %>
          </p>

          <p class="post-activity-time post-activity-text">
            <%= time_ago_in_words(activity.created_at.localtime) %> ago
          </p>
        </div>
      <% end %>

    <% end %>
  </div>

  <% if @activity.length > 13 %>
    <%= link_to "More posts...", more_activity_path(next: 13), method: :post, remote: true, id: "more-link", class: "bottom-links" %>

    <button id="top-link" class="bottom-links">Back to top</button>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div id="new-post-container">

  <div id="np-inner-div">
    <div id="post-type-links-div">
      <p class="new-post-fp"><i class="fas fa-image"></i> Image</p>

      <%= link_to new_video_post_path, class: "new-post-link-to-video" do %>
        <i class="fas fa-video"></i> Video
      <% end %>
    </div>

    <%= render "form" %>
  </div>

  <%= link_to "Back", current_user, id: "new-post-back-link" %>
</div>

app/views/posts/following_feed.html.erb
<% if @sorted_feed.length === 0 %>
  <%
    users = User.all
    temp_ary = []
    sorted_by_followers = []

    users.each do |user|
      temp_ary << { follower_count: user.followers.count, user_obj: user }
    end

    temp_ary = (temp_ary.sort_by { |x| x[:follower_count] }).reverse!

    temp_ary.each do |obj|
      sorted_by_followers << obj[:user_obj]
    end
  %>


  <div id="following-feed-no-following-container">
    <h3 id="suggested-title">Suggestions For You</h3>
    <% sorted_by_followers[0, 50].each do |user| %>
      <% @follow = Follow.find_by(user_id: current_user.id, following_id: user.id) %>
      <% next if current_user === user || @follow %>

      <div class="suggested-user-div">

        <%= link_to user, class: "suggested-avatar-link" do %>
          <% if user.avatar.attached? %> 
            <div class="suggested-avatar background-image" style="background-image: url('<%= url_for(user.avatar) %>');"></div>
          <% else %>
            <div class="suggested-avatar background-image" style="background-image: url('<%= "/assets/default_profile.jpg" %>');"></div>
          <% end %>
        <% end %>

        <div class="suggested-names">
          <%= link_to user.username, user, class: "suggested-username suggested-name-txt" %>
          <p class="suggested-name-txt"><%= "#{user.first_name} #{user.last_name}" %></p>
        </div>

        <% follow_txt = @follow ? "Unfollow" : "Follow" %>

        <%= link_to follow_txt, ajax_follows_update_follow_path(user_id: current_user.id, following_id: user.id, html_id: "follow-#{user.id}", id: 0), method: :put, remote: true, id: "follow-#{user.id}", class: "suggested-follow-link" %>
      </div>
    <% end %>
  </div>
<% else %>
  <div id="following-container">
    <div id="following-mid-container">

      <% @sorted_feed[0, 10].each do |post| %>

        <%
          all_comments = post.comments 

          temp_ary = []
          comments = []

          all_comments.each do |comment|
            temp_ary << { likes: comment.likes.count, com_obj: comment }
          end

          temp_ary = (temp_ary.sort_by { |x| x[:likes] }).reverse!
          
          temp_ary.each do |obj|
            comments << obj[:com_obj]
          end
        %>

        <div id="following-post-container">
          <% user = User.find(post.user_id) %>

          <div id="following-user-info-div">
            <% if user.avatar.attached? %> 
              <div class="following-avatar background-image" style="background-image: url('<%= url_for(user.avatar) %>');"></div>
            <% else %>
              <div class="following-avatar background-image" style="background-image: url('<%= "/assets/default_profile.jpg" %>');"></div>
            <% end %>

            <p><%= link_to user.username, user, class: "following-header-username following-un-size" %></p>
          </div>

          <% if post.class.method_defined? :image %>
            <div>
              <div class="following-feed-image background-image" style="background-image: url('<%= url_for(post.image) %>');">
              
              </div>
            </div>
          <% elsif post.class.method_defined? :clip %>
            <div class="video-container">
              <%= video_tag url_for(post.clip), controls: "", class: "following-feed-video" %>
            </div>
          <% end %>

          <div class="following-activity-options following-pad">
            <div class="following-activity-lc">
              <% if post.class.method_defined? :image %>
                <% like_exists = Like.where(post_id: post.id, user_id: current_user.id) == [] ? "far fa-heart" : "fas fa-heart  like-icon-col" %>

                <%= link_to ajax_likes_update_like_path(id: post.id, type: "post", html_id: "likeable_id_#{post.id}", html_count_id: "like_count#{post.id}"), method: :put, remote: true, class: "following-like-link foll-activity-link" do %>
                  <i id="<%= "likeable_id_#{post.id}" %>" class="<%= like_exists %>"></i>
                <% end %>  

              <% elsif post.class.method_defined? :clip %>   
                <% like_exists = Like.where(video_post_id: post.id, user_id: current_user.id) == [] ? "far fa-heart" : "fas fa-heart like-icon-col" %>

                <%= link_to ajax_likes_update_like_path(id: post.id, type: "video post", html_id: "video_likeable_id_#{post.id}", html_count_id: "video_like_count#{post.id}"), method: :put, remote: true, class: "following-like-link foll-activity-link" do %>
                  <i id="<%= "video_likeable_id_#{post.id}" %>" class="<%= like_exists %>"></i>
                <% end %>
              <% end %>

              <%= link_to post do %>
                <i class="far fa-comment foll-activity-link"></i>
              <% end %>          
            </div>

            <% unless current_user === user %>
              <% if post.class.method_defined? :image %>
                <% save_exists = SavedPost.where(user_id: current_user.id, post_id: post.id) === [] ? "far fa-bookmark" : "fas fa-bookmark" %>

                <%= link_to ajax_saved_posts_saved_post_path(user_id: current_user.id, id: post.id, type: "image", html_id: "saveable_post_id_#{post.id}"), method: :put, remote: true, class: "foll-activity-link" do %>
                  <i id="<%= "saveable_post_id_#{post.id}" %>" class="<%= save_exists %>"></i>
                <% end %>
              <% elsif post.class.method_defined? :clip %>
                  <% save_exists = SavedPost.where(user_id: current_user.id, video_post_id: post.id) === [] ? "far fa-bookmark" : "fas fa-bookmark" %>

                  <%= link_to ajax_saved_posts_saved_post_path(user_id: current_user.id, id: post.id, type: "video", html_id: "saveable_video_post_id_#{post.id}"), method: :put, remote: true, class: "foll-activity-link" do %>
                    <i id="<%= "saveable_video_post_id_#{post.id}" %>" class="<%= save_exists %>"></i>
                  <% end %>
              <% end %>
            <% else %>
              <div></div>
            <% end %>
          </div>

          <div class="following-pad">
            <% if post.class.method_defined? :image %>
              <h3 id=<%= "like_count#{post.id}" %> class="following-like-count">
                <%= "#{post.likes.count} like".pluralize(post.likes.count) %>
              </h3>
            <% elsif post.class.method_defined? :clip %>
              <h3 id=<%= "video_like_count#{post.id}" %> class="following-like-count">
                <%= "#{post.likes.count} like".pluralize(post.likes.count) %>
              </h3>
            <% end %>
          </div>

          <div class="following-pad">
            <% unless post.caption === "" %>
              <p class="following-base-fsize following-word-wrap">
                <strong>
                  <%= link_to user.username, user, class: "following-header-username" %>
                </strong> 
                <% if post.caption.length > 150 %>
                  <%= post.caption[0..150] %><span class="show-more">...Show More</span><span class="more-content"><%= post.caption[150..post.caption.length] %></span><span class="show-less">...Show Less</span>
                <% else %>
                  <%= post.caption %>
                <% end %>
              </p>
            <% end %>
          </div>

          <% if post.class.method_defined? :image %>
            <% com_div_id = "image-comment-div-#{post.id}" %>
            <% com_input_id = "image-feed-text-field-#{post.id}" %>
          <% elsif post.class.method_defined? :clip %>
            <% com_div_id = "video-comment-div-#{post.id}" %>
            <% com_input_id = "video-feed-text-field-#{post.id}" %>
          <% end %>

          <div id=<%= com_div_id %>>
            <% unless post.comments.count === 0 %>

              <%= link_to "View all #{post.comments.count} " + "comment".pluralize(post.comments.count), post, class: "following-pad following-base-fsize following-gray-txt" %>

              <% comments.slice(0, 3).each do |comment| %>
                <% user_com = User.find(comment.user_id) %>

                <p class="following-word-wrap following-pad following-base-fsize">
                  <strong>
                    <%= link_to user_com.username, user_com, class: "following-header-username" %>
                  </strong> 
                  <% if comment.body.length > 150 %>
                    <%= comment.body[0..150] %><span class="show-more">...Show More</span><span class="more-content"><%= comment.body[150..comment.body.length] %></span><span class="show-less">...Show Less</span>
                  <% else %>
                    <%= comment.body %>
                  <% end %>
                </p>
              <% end %>
            <% end %>
          </div>

          <div class="following-pad following-pdate following-gray-txt">
            <%= "#{time_ago_in_words(post.created_at.localtime)} ago"  %>
          </div>

          <% if post.class.method_defined? :image %>
            <%= form_for [ post, @comment ], url: ajax_feed_comment_post_comment_path(id: 0, post_id: post.id, video_post_id: 0, type: "image", html_id: com_div_id, html_input: com_input_id), html: {remote: true, class: "following-feed-comment-form"} do |f| %>

              <%= f.text_field :body, placeholder: "Add a comment...", id: com_input_id, class: "following-comment-input", required: true, maxlength: 2200 %>

              <%= f.submit "Post", class: "following-form-comment-submit" %>
            <% end %>
          <% elsif post.class.method_defined? :clip %>
            <%= form_for [ post, @comment ], url: ajax_feed_comment_post_comment_path(id: 0, post_id: 0, video_post_id: post.id, type: "video", html_id: com_div_id, html_input: com_input_id), html: {remote: true, class: "following-feed-comment-form"} do |f| %>

              <%= f.text_field :body, placeholder: "Add a comment...", id: com_input_id, class: "following-comment-input", required: true, maxlength: 2200 %>

              <%= f.submit "Post", class: "following-form-comment-submit" %>
            <% end %>
          <% end %>
        </div>

      <% end %>
    </div>
  </div>

  <% if @sorted_feed.length > 10 %>
    <%= link_to "More posts...", more_following_path(posts: 0, next: 10), method: :post, remote: true, id: "more-link", class: "bottom-links" %>

    <button id="top-link" class="bottom-links">Back to top</button>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<% if @sorted_by_likes.length === 0 %>
  <div class="user-show-no-posts">
    <i class="fas fa-camera user-show-no-posts-camera"></i>
    <h2 class="user-show-no-posts-title-current-user">No Posts Yet</h2>
    <%= link_to "Share", new_post_path, id: "user-show-add-post-current-user" %>
  </div>
<% else %>
  <div id="post-index-container">
    <div class="post-display-grid">
      <% @sorted_by_likes[0, 21].each do |post| %>
        <% if post.class.method_defined? :image %>
          <%= link_to post, class: "pi-tile-link" do %>
            <div class="post-index-tile-div background-image" style="background-image: url('<%= url_for(post.image) %>');">
              <div class="tinted-tile">
                <p class="post-index-info">
                  <i class="fas fa-heart"></i>
                  <span class="pi-like-span">
                    <%= post.likes.count %>
                  </span>
                  
                  <i class="fas fa-comment"></i>
                  <span class="pi-comment-span">
                    <%= post.comments.count %>
                  </span>
                </p>
              </div>
            </div>
          <% end %>
        <% elsif post.class.method_defined? :clip %>
          <%= link_to post, class: "pi-tile-link" do %>
            <div class="post-index-tile-div video-container">
              <%= video_tag url_for(post.clip), class: "post-index-content post-index-video" %>
              <div class="tinted-tile">
                <p class="post-index-info">
                  <i class="fas fa-heart"></i>
                  <span class="pi-like-span">
                    <%= post.likes.count %>
                  </span>

                  <i class="fas fa-comment"></i>
                  <span class="pi-comment-span">
                    <%= post.comments.count %>
                  </span>
                </p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if @sorted_by_likes.length > 21 %>
    <%= link_to "More posts...", more_index_posts_path(next: 21), method: :post, remote: true, id: "more-link", class: "bottom-links" %>

    <button id="top-link" class="bottom-links">Back to top</button>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<div id="new-post-container">

  <div id="np-inner-div">
    <div id="post-type-links-div">
      <p class="new-post-fp"><i class="fas fa-image"></i> Image</p>

      <%= link_to new_video_post_path, class: "new-post-link-to-video" do %>
        <i class="fas fa-video"></i> Video
      <% end %>
    </div>
    

    <%= render "form" %>
  </div>

  <%= link_to "Back", current_user, id: "new-post-back-link" %>
</div>