config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "registrations"
  }

  devise_scope :user do
    authenticated :user do
      root 'posts#following_feed', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show]
  post "more_user_index", to: "users#more_user_index", as: :more_user_index
  post "more_user_show_posts/:id", to: "users#more_user_show_posts", as: :more_user_show_posts

  resources :posts
  post "more_index_posts", to: "posts#more_index_posts", as: :more_index_posts

  resources :posts do
    resources :comments, only: [:create, :update, :destroy] do
      member do
        post :ajax_feed_comment
      end
    end
  end

  post "more_comments/:post_id", to: "comments#more_comments", as: :more_comments

  get "/following_feed", to: "posts#following_feed"
  post "more_following_posts/:posts", to: "posts#more_following", as: :more_following

  get "/activity", to: "posts#activity"
  post "more_activity", to: "posts#more_activity", as: :more_activity

  get "/saved_posts", to: "saved_posts#saved_posts"
  post "more_saved_posts", to: "saved_posts#more_saved_posts", as: :more_saved_posts

  resources :video_posts

  resources :video_posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :likes, only: [:update] do
    member do
      put :ajax_likes_update
    end
  end

  resources :follows, only: [:update] do
    member do
      put :ajax_follows_update
    end
  end

  get "followers_index/:id", to: "follows#followers_index", as: :followers_index
  get "following_index/:id", to: "follows#following_index", as: :following_index

  resources :saved_posts, only: [:update] do
    member do
      put :ajax_saved_posts
    end
  end

  resources :conversations do
    resources :messages
  end

  post "more_conversations", to: "conversations#more_conversations", as: :more_conversations
end

app/views/layouts/_navbar.html.erb
 <% if user_signed_in? %>  
  <div id="nav-bar">
    <div id="inner-nav-div">

      <%= link_to following_feed_path, id: "nav-logo-link", class: "nav-link" do %>
        <%= image_tag ("/assets/logo.png"), id: "nav-logo" %>
      <% end %>

      <%= form_tag(users_path, method: :get, id: "nav-form") do %>
        <%= text_field_tag(:search, params[:search], placeholder: "search", id: "nav-search") %>

        <button id="nav-search-btn" type="submit" name="commit">
          <i class="fas fa-search"></i>
        </button>
      <% end %>

      <div id="nav-right">
        <%= link_to users_path, id: "nav-mobile-search", class: "nav-icon-link" do %>
          <i class="fas fa-search"></i>
        <% end %>

        <%= link_to new_post_path, id: "nav-home-icon-link", class: "nav-icon-link" do %>
          <i class="far fa-plus-square"></i>
        <% end %>
        
        <%= link_to conversations_path, class: "nav-icon-link" do %>
          <i class="far fa-paper-plane"></i>
        <% end %>

        <%= link_to posts_path, class: "nav-icon-link" do %>
          <i class="far fa-compass"></i>
        <% end %>

        <%= link_to activity_path, class: "nav-icon-link" do %>
          <i class="far fa-heart"></i>
        <% end %>

        <div>
          <% if current_user.avatar.attached? %> 
            <div id="nav-prof-pic" class="background-image" style="background-image: url('<%= url_for(current_user.avatar) %>');"></div>
          <% else %>
            <div id="nav-prof-pic" class="background-image" style="background-image: url('<%= "/assets/default_profile.jpg" %>');"></div>
          <% end %>

          <div id="nav-drop-content">
            <div id="drp-arrow" class="nav-drop-links">
              <i class="fas fa-chevron-up"></i>
            </div>

            <%= link_to current_user, class: "nav-drop-links" do %>
              <i class="far fa-user-circle nav-drop-links"></i>
              <span class="nav-link-txt">Profile</span>
            <% end %>

            <%= link_to saved_posts_path, class: "nav-drop-links" do %>
              <i class="far fa-bookmark nav-drop-links"></i>
              <span class="nav-link-txt">Saved</span>
            <% end %>

            <%= link_to edit_user_registration_path, class: "nav-drop-links" do %>
              <i class="fas fa-cog nav-drop-links"></i>
              <span class="nav-link-txt">Settings</span>
            <% end %>

            <%= link_to destroy_user_session_path, method: :delete, id: "nav-log-out", class: "nav-drop" do %>
              <span class="nav-link-txt">Log Out</span>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
<% else %>
  <div id="nav-bar">
    <div id="nav-sign-out">
      <%= image_tag ("/assets/logo.png"), id: "nav-logo" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/c35c8e97b3.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div id="nav-clearance">
      <%= yield %>
    </div>
  </body>
</html>